[package]
name = "yog-node"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yog-erasure = { path = "../yog-erasure" }
yog-store = { path = "../yog-store" }
yog-transport = { path = "../yog-transport" }
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
tokio.workspace = true
tracing-subscriber.workspace = true
