[package]
name = "nauka-raft"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nauka-erasure = { path = "../nauka-erasure" }
nauka-transport = { path = "../nauka-transport" }
nauka-cluster = { path = "../nauka-cluster" }
nauka-s3 = { path = "../nauka-s3" }
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
metrics.workspace = true
async-trait = "0.1"
bincode = "1"
openraft = { version = "0.9", features = ["serde", "storage-v2"] }
redb = "2"

[dev-dependencies]
quinn = "0.11"
tempfile = "3"
nauka-store = { path = "../nauka-store" }
