[package]
name = "nauka-cluster"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nauka-erasure = { path = "../nauka-erasure" }
nauka-store = { path = "../nauka-store" }
nauka-transport = { path = "../nauka-transport" }
anyhow.workspace = true
blake3.workspace = true
metrics.workspace = true
rand = "0.8"
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
