[package]
name = "yog-discovery"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
pkarr = "3"
rcgen = "0.13"
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
mainline = "5"
tempfile = "3"
yog-transport = { path = "../yog-transport" }
