//! Resource contract — see ADR 0006.
//!
//! Every persistent resource in Nauka (`hypervisor`, `mesh`, and the
//! incoming `org`, `vpc`, `vm`, …) implements [`Resource`]. The trait
//! is normally implemented via the `#[resource(table = "…", scope =
//! "…")]` attribute macro from `nauka-core-macros`, which generates
//! the `SCHEMAFULL` DDL, validates every invariant at compile time,
//! and registers the resource into [`ALL_RESOURCES`].
//!
//! Callers do not interact with individual resources to obtain the
//! schema; they call [`local_schemas`] / [`cluster_schemas`] which
//! concatenate every registered resource's DDL filtered by [`Scope`].

use linkme::distributed_slice;
use serde::{de::DeserializeOwned, Deserialize, Deserializer, Serialize, Serializer};
use std::fmt::{self, Debug, Display, Formatter};
use std::hash::{Hash, Hasher};
use std::marker::PhantomData;
use surrealdb::types::{Kind, RecordIdKey, Value};

pub use surrealdb::types::{Datetime, SurrealValue};

#[doc(hidden)]
pub mod __macro_support {
    pub use linkme;
}

/// Escape a string for use inside a SurrealQL double-quoted string
/// literal. Escapes `"` and `\`.
pub fn escape_surql_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c => out.push(c),
        }
    }
    out
}

/// Escape a value for use inside a SurrealDB `⟨…⟩` record-id
/// payload. Escapes `\` and the closing bracket `⟩` so an attacker
/// controlling an id string cannot break out of the record literal.
pub fn escape_record_id(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\u{27E9}' => out.push_str("\\\u{27E9}"),
            c => out.push(c),
        }
    }
    out
}

/// Convert a PascalCase type identifier (e.g. `Hypervisor`, `VmImage`)
/// into the snake_case SurrealDB table name (`hypervisor`,
/// `vm_image`). Used by `#[resource]` and `#[references]` so
/// `#[references(Hypervisor)]` knows the target table without the
/// author typing the name twice.
///
/// Consecutive uppercase characters are not handled specially —
/// `VMImage` becomes `v_m_image`. Resource authors must use Rust's
/// canonical PascalCase (`VmImage`) for the round-trip to work.
pub fn pascal_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for (i, c) in s.char_indices() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// Typed reference to another [`Resource`]. `Ref<Hypervisor>`
/// statically guarantees at compile time that a `Volume`'s id cannot
/// land in a field that wants a hypervisor.
///
/// Serialises transparently as the inner id string; the DDL side
/// (generated by `#[resource]`) emits `record<{table}>` for any
/// `Ref<T>` field so SurrealDB enforces referential integrity at the
/// database layer, too.
pub struct Ref<R: Resource> {
    id: String,
    _marker: PhantomData<fn() -> R>,
}

impl<R: Resource> Ref<R> {
    /// Wrap a raw id string. No validation is performed here; the
    /// referential integrity check happens at insert time against
    /// the target table.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            _marker: PhantomData,
        }
    }

    /// The id payload as `&str` — not the full `table:id` form.
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Consume and return the inner id.
    pub fn into_id(self) -> String {
        self.id
    }
}

impl<R: Resource> Debug for Ref<R> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "Ref<{}>({:?})", R::TABLE, self.id)
    }
}

impl<R: Resource> Display for Ref<R> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "{}:{}", R::TABLE, self.id)
    }
}

impl<R: Resource> Clone for Ref<R> {
    fn clone(&self) -> Self {
        Self {
            id: self.id.clone(),
            _marker: PhantomData,
        }
    }
}

impl<R: Resource> PartialEq for Ref<R> {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}
impl<R: Resource> Eq for Ref<R> {}

impl<R: Resource> Hash for Ref<R> {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl<R: Resource> Serialize for Ref<R> {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        self.id.serialize(s)
    }
}

impl<'de, R: Resource> Deserialize<'de> for Ref<R> {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        String::deserialize(d).map(Ref::new)
    }
}

impl<R: Resource> SurrealValue for Ref<R> {
    fn kind_of() -> Kind {
        // Report as string at the type level — the DDL's
        // `record<{table}>` constraint is what actually enforces the
        // reference. SurrealDB coerces a string id into the record
        // reference at insert time. Returning `Kind::Record` here
        // would break the `SurrealValue` auto-derive on any struct
        // that reads the field back as a plain string (e.g. in a
        // partial SELECT).
        Kind::String
    }

    fn into_value(self) -> Value {
        self.id.into_value()
    }

    fn from_value(value: Value) -> Result<Self, surrealdb::types::Error> {
        match value {
            // When the field is typed `record<T>` in DDL, SurrealDB
            // returns the value as a `RecordId`; extract the key.
            Value::RecordId(rid) => match rid.key {
                RecordIdKey::String(s) => Ok(Ref::new(s)),
                RecordIdKey::Number(n) => Ok(Ref::new(n.to_string())),
                other => Err(surrealdb::types::conversion_error(
                    Kind::String,
                    Value::RecordId(surrealdb::types::RecordId {
                        table: rid.table,
                        key: other,
                    }),
                )),
            },
            other => String::from_value(other).map(Ref::new),
        }
    }
}

/// Where a resource lives.
///
/// - [`Scope::Local`] — per-node SurrealKV. Schema applied on every
///   node at boot via [`local_schemas`]. Non-deterministic defaults
///   like `DEFAULT time::now()` are allowed; each node has its own
///   copy so determinism is irrelevant.
/// - [`Scope::Cluster`] — TiKV-shared storage replicated by Raft.
///   Schema applied **once**, by the bootstrap node, per ADR 0004.
///   Non-deterministic defaults are forbidden — they would make two
///   replicas compute different rows from the same Raft log entry and
///   silently break consensus.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Scope {
    Local,
    Cluster,
}

/// Compile-time descriptor for a resource type. One value per
/// `#[resource(…)]` annotation, registered into [`ALL_RESOURCES`] at
/// link time.
#[derive(Debug)]
pub struct ResourceDescriptor {
    /// SurrealDB table name (snake_case singular).
    pub table: &'static str,
    /// Where this resource lives (per-node vs cluster).
    pub scope: Scope,
    /// Full `DEFINE TABLE` / `DEFINE FIELD` / `DEFINE INDEX`
    /// SurrealQL emitted by the macro.
    pub ddl: &'static str,
    /// Non-CRUD verbs this resource declares via
    /// `#[resource(..., custom_actions = "start, stop")]`. Each entry
    /// becomes a `<table>.<action>` `Permission` record at boot. Empty
    /// for resources with only standard CRUD.
    pub custom_actions: &'static [&'static str],
}

/// Global registry of every resource defined in the workspace.
///
/// The `#[resource(…)]` attribute macro emits one
/// `#[distributed_slice(ALL_RESOURCES)]` entry per resource, so the
/// `bin/nauka` binary picks them all up at link time without anyone
/// maintaining a hand-written list.
#[distributed_slice]
pub static ALL_RESOURCES: [&'static ResourceDescriptor] = [..];

/// Compile-time descriptor for a SurrealDB `DEFINE ACCESS TYPE RECORD`
/// statement. One per `#[access(…)]` annotation — see IAM epic #344.
#[derive(Debug)]
pub struct AccessDescriptor {
    /// Access name (`DEFINE ACCESS <name> ON DATABASE …`). Must be
    /// unique across the database.
    pub name: &'static str,
    /// Full `DEFINE ACCESS … TYPE RECORD …` SurrealQL.
    pub ddl: &'static str,
}

/// Global registry of every `DEFINE ACCESS` declared via `#[access]`.
/// Applied by `bin/nauka` at DB open time, after `local_schemas` +
/// `cluster_schemas`.
#[distributed_slice]
pub static ALL_ACCESS_DEFS: [&'static AccessDescriptor] = [..];

/// Compile-time descriptor for a `DEFINE FUNCTION fn::ns::name(...) {...}`
/// SurrealQL statement — e.g. `fn::iam::can` for IAM-2 (#346).
///
/// Functions must be defined before any `DEFINE TABLE ... PERMISSIONS`
/// clause that calls them, which is why they have their own slice +
/// `function_definitions()` helper: `bin/nauka` loads them first.
#[derive(Debug)]
pub struct FunctionDescriptor {
    /// Fully-qualified function name, e.g. `"fn::iam::can"`. Used
    /// only for diagnostics and slice dedup — SurrealDB parses it
    /// out of the DDL string.
    pub name: &'static str,
    /// Full `DEFINE FUNCTION … { … } PERMISSIONS …;` SurrealQL.
    pub ddl: &'static str,
}

#[distributed_slice]
pub static ALL_DB_FUNCTIONS: [&'static FunctionDescriptor] = [..];

/// Contract every resource implements.
///
/// Normally derived through the `#[resource(…)]` attribute macro;
/// hand-written impls are possible but discouraged because they
/// bypass the compile-time invariant checks.
pub trait Resource: Serialize + DeserializeOwned + SurrealValue + Send + Sync + 'static {
    /// SurrealDB table name. snake_case singular.
    const TABLE: &'static str;

    /// Where this resource lives.
    const SCOPE: Scope;

    /// Full DDL (`DEFINE TABLE` / `FIELD` / `INDEX`) for this
    /// resource. Generated by the macro.
    const DDL: &'static str;

    /// Type of the natural key (`#[id]` field).
    type Id: Display + Send + Sync;

    /// Natural key value. Used to build the SurrealDB record id
    /// (`{TABLE}:⟨{id}⟩`).
    fn id(&self) -> &Self::Id;

    /// Set by the writer at creation time. Never produced by a
    /// `DEFAULT time::now()` clause for `Scope::Cluster` resources.
    fn created_at(&self) -> &Datetime;

    /// Bumped by the generated `update` helper on every save.
    fn updated_at(&self) -> &Datetime;

    /// `0` on create, `+1` on every successful update. Provides
    /// optimistic concurrency and a deterministic ordering of writes.
    fn version(&self) -> u64;
}

/// SurrealQL statement factory for a [`Resource`]. The `#[resource]`
/// attribute macro emits an `impl ResourceOps for …` that provides
/// the two per-field methods ([`create_query`](ResourceOps::create_query)
/// and [`update_query`](ResourceOps::update_query)); the rest are
/// default methods that only need `Self::TABLE` and `Self::Id`.
///
/// `nauka_state::Writer` consumes these strings and routes them to
/// either `RaftNode::write` (for [`Scope::Cluster`]) or
/// `Database::query` (for [`Scope::Local`]), so call sites never pick
/// the transport themselves.
pub trait ResourceOps: Resource + Sized {
    /// SurrealQL `CREATE` statement for this value. Uses the natural
    /// key as the record id: `CREATE {table}:⟨{id}⟩ SET …`.
    ///
    /// Emitted by `#[resource]`; no default implementation because
    /// the body is per-field.
    fn create_query(&self) -> String;

    /// SurrealQL `UPDATE` statement setting every field on the
    /// record identified by this value's natural key. The caller is
    /// responsible for having bumped `updated_at` / `version` before
    /// calling — this is not done inside the generated method, so
    /// callers that need deterministic timestamps (Raft leaders) can
    /// set them explicitly.
    fn update_query(&self) -> String;

    /// Overwrite the `created_at` field. Generated by the
    /// `#[resource]` macro — callers building a resource for
    /// creation should set this to the same value they use for
    /// `set_updated_at` to keep the timestamps symmetrical on
    /// insert.
    fn set_created_at(&mut self, dt: Datetime);

    /// Overwrite the `updated_at` field. Bumped on every successful
    /// update — the generic [`crate::api`]-driven handler stack
    /// calls this with `Datetime::now()` so the leader's timestamp
    /// replicates identically through Raft.
    fn set_updated_at(&mut self, dt: Datetime);

    /// Overwrite the `version` counter. `0` on create; on update
    /// the caller passes `previous.version + 1` to maintain the
    /// optimistic-concurrency invariant the `#[resource]` contract
    /// relies on.
    fn set_version(&mut self, v: u64);

    /// SurrealQL `DELETE` for the record with this id.
    fn delete_query(id: &Self::Id) -> String {
        format!(
            "DELETE {}:\u{27E8}{}\u{27E9}",
            Self::TABLE,
            escape_record_id(&id.to_string())
        )
    }

    /// SurrealQL `SELECT *` for the single record with this id.
    fn get_query(id: &Self::Id) -> String {
        format!(
            "SELECT * FROM {}:\u{27E8}{}\u{27E9}",
            Self::TABLE,
            escape_record_id(&id.to_string())
        )
    }

    /// SurrealQL `SELECT *` for every record in this resource's
    /// table.
    fn list_query() -> String {
        format!("SELECT * FROM {}", Self::TABLE)
    }
}

/// Concatenated DDL for every [`Scope::Local`] resource, ready to
/// pass to `db.query(&…)` on every node at boot.
pub fn local_schemas() -> String {
    schemas_for(Scope::Local)
}

/// Concatenated DDL for every [`Scope::Cluster`] resource, applied
/// once by the bootstrap node per ADR 0004.
pub fn cluster_schemas() -> String {
    schemas_for(Scope::Cluster)
}

fn schemas_for(scope: Scope) -> String {
    let mut out = String::new();
    for desc in ALL_RESOURCES.iter().filter(|d| d.scope == scope) {
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(desc.ddl);
    }
    out
}

/// Concatenated DDL for every `#[access]`-declared `DEFINE ACCESS`
/// statement. Passed to `nauka_state::load_schemas` at DB open time so
/// every node has the same access surface.
pub fn access_definitions() -> String {
    let mut out = String::new();
    for desc in ALL_ACCESS_DEFS.iter() {
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(desc.ddl);
    }
    out
}

/// Concatenated DDL for every `DEFINE FUNCTION` registered in
/// [`ALL_DB_FUNCTIONS`]. Load *before* the table DDL so any
/// `PERMISSIONS` clause that calls a function can resolve it at
/// parse time.
pub fn function_definitions() -> String {
    let mut out = String::new();
    for desc in ALL_DB_FUNCTIONS.iter() {
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(desc.ddl);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_registry_returns_empty_string() {
        // nauka-core defines no resources of its own, so when built in
        // isolation the registry is empty. The helpers must still
        // return a valid empty String (no panic, no leading separator).
        assert_eq!(local_schemas(), "");
        assert_eq!(cluster_schemas(), "");
        assert_eq!(access_definitions(), "");
        assert_eq!(function_definitions(), "");
    }

    #[test]
    fn scope_round_trip() {
        assert_ne!(Scope::Local, Scope::Cluster);
        assert_eq!(Scope::Local, Scope::Local);
    }
}
