//! Resource contract — see ADR 0006.
//!
//! Every persistent resource in Nauka (`hypervisor`, `mesh`, and the
//! incoming `org`, `vpc`, `vm`, …) implements [`Resource`]. The trait
//! is normally implemented via the `#[resource(table = "…", scope =
//! "…")]` attribute macro from `nauka-core-macros`, which generates
//! the `SCHEMAFULL` DDL, validates every invariant at compile time,
//! and registers the resource into [`ALL_RESOURCES`].
//!
//! Callers do not interact with individual resources to obtain the
//! schema; they call [`local_schemas`] / [`cluster_schemas`] which
//! concatenate every registered resource's DDL filtered by [`Scope`].

use linkme::distributed_slice;
use serde::{de::DeserializeOwned, Serialize};
use std::fmt::Display;
use surrealdb::types::Datetime;

/// Where a resource lives.
///
/// - [`Scope::Local`] — per-node SurrealKV. Schema applied on every
///   node at boot via [`local_schemas`]. Non-deterministic defaults
///   like `DEFAULT time::now()` are allowed; each node has its own
///   copy so determinism is irrelevant.
/// - [`Scope::Cluster`] — TiKV-shared storage replicated by Raft.
///   Schema applied **once**, by the bootstrap node, per ADR 0004.
///   Non-deterministic defaults are forbidden — they would make two
///   replicas compute different rows from the same Raft log entry and
///   silently break consensus.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Scope {
    Local,
    Cluster,
}

/// Compile-time descriptor for a resource type. One value per
/// `#[resource(…)]` annotation, registered into [`ALL_RESOURCES`] at
/// link time.
#[derive(Debug)]
pub struct ResourceDescriptor {
    /// SurrealDB table name (snake_case singular).
    pub table: &'static str,
    /// Where this resource lives (per-node vs cluster).
    pub scope: Scope,
    /// Full `DEFINE TABLE` / `DEFINE FIELD` / `DEFINE INDEX`
    /// SurrealQL emitted by the macro.
    pub ddl: &'static str,
}

/// Global registry of every resource defined in the workspace.
///
/// The `#[resource(…)]` attribute macro emits one
/// `#[distributed_slice(ALL_RESOURCES)]` entry per resource, so the
/// `bin/nauka` binary picks them all up at link time without anyone
/// maintaining a hand-written list.
#[distributed_slice]
pub static ALL_RESOURCES: [&'static ResourceDescriptor] = [..];

/// Contract every resource implements.
///
/// Normally derived through the `#[resource(…)]` attribute macro;
/// hand-written impls are possible but discouraged because they
/// bypass the compile-time invariant checks.
pub trait Resource: Serialize + DeserializeOwned + Send + Sync + 'static {
    /// SurrealDB table name. snake_case singular.
    const TABLE: &'static str;

    /// Where this resource lives.
    const SCOPE: Scope;

    /// Full DDL (`DEFINE TABLE` / `FIELD` / `INDEX`) for this
    /// resource. Generated by the macro.
    const DDL: &'static str;

    /// Type of the natural key (`#[id]` field).
    type Id: Display + Send + Sync;

    /// Natural key value. Used to build the SurrealDB record id
    /// (`{TABLE}:⟨{id}⟩`).
    fn id(&self) -> &Self::Id;

    /// Set by the writer at creation time. Never produced by a
    /// `DEFAULT time::now()` clause for `Scope::Cluster` resources.
    fn created_at(&self) -> &Datetime;

    /// Bumped by the generated `update` helper on every save.
    fn updated_at(&self) -> &Datetime;

    /// `0` on create, `+1` on every successful update. Provides
    /// optimistic concurrency and a deterministic ordering of writes.
    fn version(&self) -> u64;
}

/// Concatenated DDL for every [`Scope::Local`] resource, ready to
/// pass to `db.query(&…)` on every node at boot.
pub fn local_schemas() -> String {
    schemas_for(Scope::Local)
}

/// Concatenated DDL for every [`Scope::Cluster`] resource, applied
/// once by the bootstrap node per ADR 0004.
pub fn cluster_schemas() -> String {
    schemas_for(Scope::Cluster)
}

fn schemas_for(scope: Scope) -> String {
    let mut out = String::new();
    for desc in ALL_RESOURCES.iter().filter(|d| d.scope == scope) {
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(desc.ddl);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_registry_returns_empty_string() {
        // nauka-core defines no resources of its own, so when built in
        // isolation the registry is empty. The helpers must still
        // return a valid empty String (no panic, no leading separator).
        assert_eq!(local_schemas(), "");
        assert_eq!(cluster_schemas(), "");
    }

    #[test]
    fn scope_round_trip() {
        assert_ne!(Scope::Local, Scope::Cluster);
        assert_eq!(Scope::Local, Scope::Local);
    }
}
