[DEFAULT]
host = 127.0.0.1
port = 8000
is_secure = False
ssl_verify = False

[fixtures]
bucket prefix = s3t-{random}-
iam name prefix = s3-tests-
iam path prefix = /s3-tests/

[s3 main]
display_name = M. Tester
user_id = testid
email = tester@ceph.com
api_name = default
access_key = 0555b35654ad1656d804
secret_key = h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==

[s3 alt]
display_name = john.doe
user_id = 56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234
email = john.doe@example.com
access_key = NOPQRSTUVWXYZABCDEFG
secret_key = nopqrstuvwxyzabcdefghijklmnopqrstuvwxyz1

[s3 tenant]
tenant = testx
display_name = testx$tenanteduser
user_id = 9876543210abcdef0123456789abcdef0123456789abcdef0123456789abcdef
email = tenanteduser@example.com
access_key = HIJKLMNOPQRSTUVWXYZA
secret_key = opqrstuvwxyzabcdefghijklmnopqrstuvwxyzab

[iam]
email = s3@example.com
user_id = 9876543210abcdef0123456789abcdef0123456789abcdef0123456789abcdef
access_key = ABCDEFGHIJKLMNOPQRST
secret_key = abcdefghijklmnopqrstuvwxyzabcdefghijklmn
display_name = youruseridhere

[s3 cloud]
host = 127.0.0.1
port = 8000
access_key = 0555b35654ad1656d804
secret_key = h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==
cloud_storage_class = CLOUD
retain_head_object = false
storage_class = STANDARD
bucket = cloud-bucket

[iam root]
access_key = AAAAAAAAAAAAAAAAAAAa
secret_key = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
user_id = RGW11111111111111111
email = rootemail@example.com
display_name = root

[iam alt root]
access_key = BBBBBBBBBBBBBBBBBBBb
secret_key = bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
user_id = RGW22222222222222222
email = altrootemail@example.com
display_name = alt-root
