//! DHT rendezvous on a local Mainline (in-process testnet, no internet):
//! deterministic derivation, publishing, resolving.

use nauka_discovery::{derive_dht_keypair, make_client, publish_seeds, resolve_seeds};

#[tokio::test]
async fn derive_publish_resolve_roundtrip() {
    // Real cluster key (generated by nauka-transport).
    let keys = tempfile::tempdir().unwrap();
    nauka_transport::generate_cluster_ca(keys.path()).unwrap();

    // Deterministic derivation: two holders of the keys end up with the same
    // DHT identity.
    let kp1 = derive_dht_keypair(keys.path()).unwrap();
    let kp2 = derive_dht_keypair(keys.path()).unwrap();
    assert_eq!(kp1.public_key(), kp2.public_key());

    // Another cluster derives a different identity.
    let other_keys = tempfile::tempdir().unwrap();
    nauka_transport::generate_cluster_ca(other_keys.path()).unwrap();
    let kp_other = derive_dht_keypair(other_keys.path()).unwrap();
    assert_ne!(kp1.public_key(), kp_other.public_key());

    // Local DHT: 8 in-process mainline nodes.
    let testnet = mainline::Testnet::new(8).unwrap();
    let publisher = make_client(Some(&testnet.bootstrap)).unwrap();
    let resolver = make_client(Some(&testnet.bootstrap)).unwrap();

    // The "leader" publishes the seeds; a newcomer (which only knows the
    // cluster keys) resolves them.
    let seeds = vec![
        "10.0.0.1:7311".parse().unwrap(),
        "10.0.0.2:7311".parse().unwrap(),
    ];
    publish_seeds(&publisher, &kp1, &seeds).await.unwrap();

    let resolved = resolve_seeds(&resolver, &kp2.public_key()).await.unwrap();
    assert_eq!(resolved, seeds);

    // Republishing with a new view (membership has changed): the resolver
    // sees the most recent version.
    let seeds2 = vec![
        "10.0.0.1:7311".parse().unwrap(),
        "10.0.0.2:7311".parse().unwrap(),
        "10.0.0.3:7311".parse().unwrap(),
    ];
    publish_seeds(&publisher, &kp1, &seeds2).await.unwrap();
    let resolved2 = resolve_seeds(&resolver, &kp1.public_key()).await.unwrap();
    assert_eq!(resolved2, seeds2);

    // A foreign cluster finds nothing under ITS key.
    let nothing = resolve_seeds(&resolver, &kp_other.public_key())
        .await
        .unwrap();
    assert!(nothing.is_empty());

    // IP auto-detection through the DHT (BEP42): on the local testnet, the
    // nodes see us from the loopback.
    let detected = nauka_discovery::detect_public_ip(Some(&testnet.bootstrap))
        .await
        .unwrap();
    assert_eq!(detected, Some("127.0.0.1".parse().unwrap()));
}
