//! ZeroFS service management — install, configure, start, stop.
//!
//! One ZeroFS instance per region on each node.
//! Service name: nauka-zerofs-{region} (e.g., nauka-zerofs-eu)

use std::path::Path;
use std::process::Command;

use nauka_core::error::NaukaError;

use super::region::RegionStorage;

const ZEROFS_BIN: &str = "/usr/local/bin/zerofs";
const ZEROFS_CONF_DIR: &str = "/etc/nauka/zerofs";
const ZEROFS_DATA_DIR: &str = "/var/lib/nauka/zerofs";
const ZEROFS_MOUNT_DIR: &str = "/mnt/nauka";

/// Check if zerofs binary is installed.
pub fn is_installed() -> bool {
    Path::new(ZEROFS_BIN).exists()
}

/// Install ZeroFS binary from GitHub releases.
pub fn ensure_installed() -> Result<(), NaukaError> {
    if is_installed() {
        return Ok(());
    }

    // Determine the correct binary name inside the tarball
    let arch = std::env::consts::ARCH;
    let bin_name = match arch {
        "x86_64" => "zerofs-linux-amd64-pgo",
        "aarch64" => "zerofs-linux-arm64-pgo",
        _ => {
            return Err(NaukaError::internal(format!(
                "unsupported architecture for zerofs: {arch}"
            )));
        }
    };

    // Download tarball and extract the right binary
    let script = format!(
        "set -e && \
         tmpdir=$(mktemp -d) && \
         curl -fsSL https://github.com/barre/zerofs/releases/latest/download/zerofs-pgo-multiplatform.tar.gz \
           -o \"$tmpdir/zerofs.tar.gz\" && \
         tar xzf \"$tmpdir/zerofs.tar.gz\" -C \"$tmpdir\" {bin_name} && \
         mv \"$tmpdir/{bin_name}\" {ZEROFS_BIN} && \
         chmod +x {ZEROFS_BIN} && \
         rm -rf \"$tmpdir\""
    );

    let output = Command::new("sh")
        .args(["-c", &script])
        .output()
        .map_err(|e| NaukaError::internal(format!("zerofs download failed: {e}")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(NaukaError::internal(format!(
            "failed to install zerofs: {stderr}"
        )));
    }

    if !is_installed() {
        return Err(NaukaError::internal(
            "zerofs installed but binary not found",
        ));
    }

    Ok(())
}

/// Generate ZeroFS TOML config for a region.
pub fn generate_config(region: &RegionStorage) -> String {
    let endpoint_line = if region.s3_endpoint.is_empty() {
        String::new()
    } else {
        format!("endpoint = \"{}\"", region.s3_endpoint)
    };

    let allow_http = if region.s3_endpoint.starts_with("http://") {
        "allow_http = \"true\""
    } else {
        ""
    };

    let s3_region_line = if region.s3_region.is_empty() {
        String::new()
    } else {
        format!("default_region = \"{}\"", region.s3_region)
    };

    format!(
        r#"# ZeroFS configuration for region: {region}
# Auto-generated by nauka

[cache]
dir = "{data_dir}/{region}"
disk_size_gb = 10.0
memory_size_gb = 1.0

[storage]
url = "s3://{bucket}/zerofs-{region}"
encryption_password = "{encryption_password}"

[aws]
access_key_id = "{access_key}"
secret_access_key = "{secret_key}"
{endpoint_line}
{s3_region_line}
{allow_http}

[servers.nbd]
addresses = ["127.0.0.1:10809"]
unix_socket = "/tmp/zerofs-{region}.nbd.sock"

[servers.rpc]
addresses = ["127.0.0.1:7000"]
unix_socket = "/tmp/zerofs-{region}.rpc.sock"

[filesystem]
compression = "lz4"

[telemetry]
enabled = false
"#,
        region = region.region,
        bucket = region.s3_bucket,
        access_key = region.s3_access_key,
        secret_key = region.s3_secret_key,
        encryption_password = region.encryption_password,
        endpoint_line = endpoint_line,
        s3_region_line = s3_region_line,
        allow_http = allow_http,
        data_dir = ZEROFS_DATA_DIR,
    )
}

/// Generate systemd unit for a region's ZeroFS instance.
fn generate_unit(region: &str) -> String {
    let conf_path = format!("{ZEROFS_CONF_DIR}/{region}.toml");
    format!(
        r#"[Unit]
Description=Nauka ZeroFS Storage ({region})
After=network-online.target nauka-wg.service
Wants=network-online.target

[Service]
Type=simple
ExecStart={ZEROFS_BIN} run -c {conf_path}
Restart=on-failure
RestartSec=5
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target
"#
    )
}

fn service_name(region: &str) -> String {
    format!("nauka-zerofs-{region}")
}

fn unit_path(region: &str) -> String {
    format!("/etc/systemd/system/nauka-zerofs-{region}.service")
}

fn conf_path(region: &str) -> String {
    format!("{ZEROFS_CONF_DIR}/{region}.toml")
}

/// Install ZeroFS config + systemd unit for a region.
pub fn install_region(config: &RegionStorage) -> Result<(), NaukaError> {
    std::fs::create_dir_all(ZEROFS_CONF_DIR).map_err(NaukaError::from)?;
    std::fs::create_dir_all(format!("{ZEROFS_DATA_DIR}/{}", config.region))
        .map_err(NaukaError::from)?;
    std::fs::create_dir_all(format!("{ZEROFS_MOUNT_DIR}/{}", config.region))
        .map_err(NaukaError::from)?;

    // Write config
    let conf = generate_config(config);
    std::fs::write(conf_path(&config.region), &conf).map_err(NaukaError::from)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(
            conf_path(&config.region),
            std::fs::Permissions::from_mode(0o600),
        );
    }

    // Write systemd unit
    let unit = generate_unit(&config.region);
    std::fs::write(unit_path(&config.region), &unit).map_err(NaukaError::from)?;

    run_systemctl(&["daemon-reload"])?;

    Ok(())
}

/// Start ZeroFS for a region.
pub fn start_region(region: &str) -> Result<(), NaukaError> {
    run_systemctl(&["enable", "--now", &service_name(region)])
}

/// Stop ZeroFS for a region.
pub fn stop_region(region: &str) -> Result<(), NaukaError> {
    let _ = run_systemctl(&["stop", &service_name(region)]);
    Ok(())
}

/// Check if ZeroFS is active for a region.
pub fn is_region_active(region: &str) -> bool {
    Command::new("systemctl")
        .args(["is-active", "--quiet", &service_name(region)])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Uninstall ZeroFS for a region.
pub fn uninstall_region(region: &str) -> Result<(), NaukaError> {
    let _ = run_systemctl(&["disable", "--now", &service_name(region)]);
    let _ = std::fs::remove_file(unit_path(region));
    let _ = std::fs::remove_file(conf_path(region));
    let _ = std::fs::remove_dir_all(format!("{ZEROFS_DATA_DIR}/{region}"));
    let _ = run_systemctl(&["daemon-reload"]);
    Ok(())
}

/// Uninstall all ZeroFS instances.
pub fn uninstall_all() -> Result<(), NaukaError> {
    // Find all zerofs unit files
    if let Ok(entries) = std::fs::read_dir("/etc/systemd/system") {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with("nauka-zerofs-") && name.ends_with(".service") {
                let svc = name.trim_end_matches(".service");
                let _ = run_systemctl(&["disable", "--now", svc]);
                let _ = std::fs::remove_file(entry.path());
            }
        }
    }

    let _ = std::fs::remove_dir_all(ZEROFS_CONF_DIR);
    let _ = std::fs::remove_dir_all(ZEROFS_DATA_DIR);
    let _ = std::fs::remove_dir_all(ZEROFS_MOUNT_DIR);
    let _ = run_systemctl(&["daemon-reload"]);

    Ok(())
}

fn run_systemctl(args: &[&str]) -> Result<(), NaukaError> {
    let output = Command::new("systemctl")
        .args(args)
        .output()
        .map_err(|e| NaukaError::internal(format!("systemctl failed: {e}")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(NaukaError::internal(format!(
            "systemctl {} failed: {}",
            args.join(" "),
            stderr.trim()
        )));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_region() -> RegionStorage {
        RegionStorage {
            region: "eu".into(),
            s3_endpoint: "https://s3.eu-central.hetzner.com".into(),
            s3_bucket: "nauka-eu".into(),
            s3_access_key: "AKID123".into(),
            s3_secret_key: "SECRET456".into(),
            s3_region: "eu-central-1".into(),
            encryption_password: "test-password-123".into(),
            is_default: true,
        }
    }

    #[test]
    fn generate_config_has_s3() {
        let conf = generate_config(&test_region());
        assert!(conf.contains("s3.eu-central.hetzner.com"));
        assert!(conf.contains("s3://nauka-eu/zerofs-eu"));
        assert!(conf.contains("eu-central-1"));
        assert!(conf.contains("[cache]"));
        assert!(conf.contains("[aws]"));
        assert!(conf.contains("lz4"));
        // Credentials are in the config (file is 0o600)
        assert!(conf.contains("AKID123"));
        assert!(conf.contains("SECRET456"));
    }

    #[test]
    fn generate_unit_no_inline_creds() {
        let unit = generate_unit("eu");
        assert!(!unit.contains("ZEROFS_S3_ACCESS_KEY"));
        assert!(unit.contains("zerofs run"));
        assert!(unit.contains("nauka-wg.service"));
    }

    #[test]
    fn service_name_format() {
        assert_eq!(service_name("eu"), "nauka-zerofs-eu");
        assert_eq!(service_name("us-east"), "nauka-zerofs-us-east");
    }

    #[test]
    fn unit_path_format() {
        assert_eq!(
            unit_path("eu"),
            "/etc/systemd/system/nauka-zerofs-eu.service"
        );
    }

    #[test]
    fn conf_path_format() {
        assert_eq!(conf_path("eu"), "/etc/nauka/zerofs/eu.toml");
    }

    #[test]
    fn is_installed_check() {
        // On test system, zerofs is likely not installed
        let _ = is_installed();
    }
}
