//! ZeroFS service management — install, configure, start, stop.
//!
//! One ZeroFS instance per region on each node.
//! Service name: nauka-zerofs-{region} (e.g., nauka-zerofs-eu)

use std::path::Path;
use std::process::Command;

use nauka_core::error::NaukaError;

use super::region::RegionStorage;

const ZEROFS_BIN: &str = "/usr/local/bin/zerofs";
const ZEROFS_CONF_DIR: &str = "/etc/nauka/zerofs";
const ZEROFS_DATA_DIR: &str = "/var/lib/nauka/zerofs";
const ZEROFS_MOUNT_DIR: &str = "/mnt/nauka";

/// Check if zerofs binary is installed.
pub fn is_installed() -> bool {
    Path::new(ZEROFS_BIN).exists()
}

/// Install ZeroFS binary.
pub fn ensure_installed() -> Result<(), NaukaError> {
    if is_installed() {
        return Ok(());
    }

    eprintln!("  Installing ZeroFS...");

    // Try cargo-binstall first (fast, pre-compiled), fallback to cargo install
    let output = Command::new("sh")
        .args(["-c", &format!(
            "curl -fsSL https://github.com/barre/zerofs/releases/latest/download/zerofs-$(uname -m)-unknown-linux-gnu -o {ZEROFS_BIN} && chmod +x {ZEROFS_BIN}"
        )])
        .output()
        .map_err(|e| NaukaError::internal(format!("zerofs download failed: {e}")))?;

    if !output.status.success() {
        // Fallback: try cargo install
        let cargo = Command::new("sh")
            .args(["-c", "cargo install zerofs 2>&1"])
            .output()
            .map_err(|e| NaukaError::internal(format!("cargo install zerofs failed: {e}")))?;

        if !cargo.status.success() {
            return Err(NaukaError::internal(
                "failed to install zerofs. Install manually: cargo install zerofs",
            ));
        }
    }

    if !is_installed() {
        return Err(NaukaError::internal(
            "zerofs installed but binary not found",
        ));
    }

    eprintln!("  ZeroFS installed");
    Ok(())
}

/// Generate ZeroFS TOML config for a region.
pub fn generate_config(region: &RegionStorage) -> String {
    format!(
        r#"# ZeroFS configuration for region: {region}
# Auto-generated by nauka

[storage]
type = "s3"
endpoint = "{endpoint}"
bucket = "{bucket}"
access_key = "${{ZEROFS_S3_ACCESS_KEY}}"
secret_key = "${{ZEROFS_S3_SECRET_KEY}}"
region = "{s3_region}"

[cache]
path = "{data_dir}/{region}"
size = "10GB"

[encryption]
enabled = true

[compression]
algorithm = "lz4"

[nfs]
enabled = false

[nbd]
enabled = true

[server]
bind = "127.0.0.1"
"#,
        region = region.region,
        endpoint = region.s3_endpoint,
        bucket = region.s3_bucket,
        s3_region = if region.s3_region.is_empty() {
            "auto"
        } else {
            &region.s3_region
        },
        data_dir = ZEROFS_DATA_DIR,
    )
}

/// Generate systemd unit for a region's ZeroFS instance.
fn generate_unit(region: &str, access_key: &str, secret_key: &str) -> String {
    let conf_path = format!("{ZEROFS_CONF_DIR}/{region}.toml");
    format!(
        r#"[Unit]
Description=Nauka ZeroFS Storage ({region})
After=network-online.target nauka-wg.service
Wants=network-online.target

[Service]
Type=simple
Environment=ZEROFS_S3_ACCESS_KEY={access_key}
Environment=ZEROFS_S3_SECRET_KEY={secret_key}
ExecStart={ZEROFS_BIN} run -c {conf_path}
Restart=on-failure
RestartSec=5
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target
"#
    )
}

fn service_name(region: &str) -> String {
    format!("nauka-zerofs-{region}")
}

fn unit_path(region: &str) -> String {
    format!("/etc/systemd/system/nauka-zerofs-{region}.service")
}

fn conf_path(region: &str) -> String {
    format!("{ZEROFS_CONF_DIR}/{region}.toml")
}

/// Install ZeroFS config + systemd unit for a region.
pub fn install_region(config: &RegionStorage) -> Result<(), NaukaError> {
    std::fs::create_dir_all(ZEROFS_CONF_DIR).map_err(NaukaError::from)?;
    std::fs::create_dir_all(format!("{ZEROFS_DATA_DIR}/{}", config.region))
        .map_err(NaukaError::from)?;
    std::fs::create_dir_all(format!("{ZEROFS_MOUNT_DIR}/{}", config.region))
        .map_err(NaukaError::from)?;

    // Write config
    let conf = generate_config(config);
    std::fs::write(conf_path(&config.region), &conf).map_err(NaukaError::from)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(
            conf_path(&config.region),
            std::fs::Permissions::from_mode(0o600),
        );
    }

    // Write systemd unit (creds in env vars — not in config file)
    let unit = generate_unit(&config.region, &config.s3_access_key, &config.s3_secret_key);
    std::fs::write(unit_path(&config.region), &unit).map_err(NaukaError::from)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(
            unit_path(&config.region),
            std::fs::Permissions::from_mode(0o600),
        );
    }

    run_systemctl(&["daemon-reload"])?;

    Ok(())
}

/// Start ZeroFS for a region.
pub fn start_region(region: &str) -> Result<(), NaukaError> {
    run_systemctl(&["enable", "--now", &service_name(region)])
}

/// Stop ZeroFS for a region.
pub fn stop_region(region: &str) -> Result<(), NaukaError> {
    let _ = run_systemctl(&["stop", &service_name(region)]);
    Ok(())
}

/// Check if ZeroFS is active for a region.
pub fn is_region_active(region: &str) -> bool {
    Command::new("systemctl")
        .args(["is-active", "--quiet", &service_name(region)])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Uninstall ZeroFS for a region.
pub fn uninstall_region(region: &str) -> Result<(), NaukaError> {
    let _ = run_systemctl(&["disable", "--now", &service_name(region)]);
    let _ = std::fs::remove_file(unit_path(region));
    let _ = std::fs::remove_file(conf_path(region));
    let _ = std::fs::remove_dir_all(format!("{ZEROFS_DATA_DIR}/{region}"));
    let _ = run_systemctl(&["daemon-reload"]);
    Ok(())
}

/// Uninstall all ZeroFS instances.
pub fn uninstall_all() -> Result<(), NaukaError> {
    // Find all zerofs unit files
    if let Ok(entries) = std::fs::read_dir("/etc/systemd/system") {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with("nauka-zerofs-") && name.ends_with(".service") {
                let svc = name.trim_end_matches(".service");
                let _ = run_systemctl(&["disable", "--now", svc]);
                let _ = std::fs::remove_file(entry.path());
            }
        }
    }

    let _ = std::fs::remove_dir_all(ZEROFS_CONF_DIR);
    let _ = std::fs::remove_dir_all(ZEROFS_DATA_DIR);
    let _ = std::fs::remove_dir_all(ZEROFS_MOUNT_DIR);
    let _ = run_systemctl(&["daemon-reload"]);

    Ok(())
}

fn run_systemctl(args: &[&str]) -> Result<(), NaukaError> {
    let output = Command::new("systemctl")
        .args(args)
        .output()
        .map_err(|e| NaukaError::internal(format!("systemctl failed: {e}")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(NaukaError::internal(format!(
            "systemctl {} failed: {}",
            args.join(" "),
            stderr.trim()
        )));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_region() -> RegionStorage {
        RegionStorage {
            region: "eu".into(),
            s3_endpoint: "https://s3.eu-central.hetzner.com".into(),
            s3_bucket: "nauka-eu".into(),
            s3_access_key: "AKID123".into(),
            s3_secret_key: "SECRET456".into(),
            s3_region: "eu-central-1".into(),
            is_default: true,
        }
    }

    #[test]
    fn generate_config_has_s3() {
        let conf = generate_config(&test_region());
        assert!(conf.contains("s3.eu-central.hetzner.com"));
        assert!(conf.contains("nauka-eu"));
        assert!(conf.contains("eu-central-1"));
        assert!(conf.contains("[cache]"));
        assert!(conf.contains("[encryption]"));
        assert!(conf.contains("lz4"));
        // Credentials use env vars, not hardcoded
        assert!(conf.contains("${ZEROFS_S3_ACCESS_KEY}"));
        assert!(!conf.contains("AKID123"));
    }

    #[test]
    fn generate_unit_has_creds_in_env() {
        let unit = generate_unit("eu", "AKID", "SECRET");
        assert!(unit.contains("ZEROFS_S3_ACCESS_KEY=AKID"));
        assert!(unit.contains("ZEROFS_S3_SECRET_KEY=SECRET"));
        assert!(unit.contains("zerofs run"));
        assert!(unit.contains("nauka-wg.service"));
    }

    #[test]
    fn service_name_format() {
        assert_eq!(service_name("eu"), "nauka-zerofs-eu");
        assert_eq!(service_name("us-east"), "nauka-zerofs-us-east");
    }

    #[test]
    fn unit_path_format() {
        assert_eq!(
            unit_path("eu"),
            "/etc/systemd/system/nauka-zerofs-eu.service"
        );
    }

    #[test]
    fn conf_path_format() {
        assert_eq!(conf_path("eu"), "/etc/nauka/zerofs/eu.toml");
    }

    #[test]
    fn is_installed_check() {
        // On test system, zerofs is likely not installed
        let _ = is_installed();
    }
}
